name: Flutter Pages Deployer

on:
  push:
    branches: [main]

jobs:
  build_number:
    runs-on: ubuntu-latest
    outputs:
      buildnumber: ${{ steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate Build Number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Build Number
        run: echo "Build Number - $BUILD_NUMBER"

  publish:
    needs: build_number
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Validate
        uses: peiffer-innovations/actions-flutter-validate@v1.1.3
        with:
          flutter_package: true

      - name: Web
        uses: peiffer-innovations/actions-flutter-deploy-pages@v1.5.0
        with:
          build_mode: profile
          build_number: ${{ needs.build_number.outputs.buildnumber }}
          deploy_path: web
          repo_url: https://github.com/${{ github.repository }}
          source_path: .
          token: ${{ secrets.GITHUB_TOKEN }}
